// Mã lỗi nội bộ — dùng tiếng Anh ngắn gọn
// Message trả về cho user phải là tiếng Việt (xử lý ở service/controller)

export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  GOOGLE_ID_ALREADY_EXISTS: "GOOGLE_ID_ALREADY_EXISTS",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  INVALID_GOOGLE_TOKEN: "INVALID_GOOGLE_TOKEN",
  ACCOUNT_BANNED: "ACCOUNT_BANNED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",

  // Auth middleware
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // Wallet
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  WITHDRAW_HOLD_ACTIVE: "WITHDRAW_HOLD_ACTIVE",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  DEPOSIT_DUPLICATE: "DEPOSIT_DUPLICATE",

  // Job
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOB_ALREADY_ASSIGNED: "JOB_ALREADY_ASSIGNED",
  JOB_CLOSED: "JOB_CLOSED",
  JOB_NOT_OWNED: "JOB_NOT_OWNED",
  POST_FEATURE_LOCKED: "POST_FEATURE_LOCKED",
  JOB_HAS_BIDS: "JOB_HAS_BIDS",

  // Bid
  BID_NOT_FOUND: "BID_NOT_FOUND",
  BID_SELF_NOT_ALLOWED: "BID_SELF_NOT_ALLOWED",
  BID_ALREADY_EXISTS: "BID_ALREADY_EXISTS",
  BID_FEATURE_LOCKED: "BID_FEATURE_LOCKED",
  BID_NOT_PENDING: "BID_NOT_PENDING",
  BID_NOT_OWNED: "BID_NOT_OWNED",

  // Contract
  CONTRACT_NOT_FOUND: "CONTRACT_NOT_FOUND",
  CONTRACT_INVALID_STATUS: "CONTRACT_INVALID_STATUS",
  CONTRACT_NOT_PARTICIPANT: "CONTRACT_NOT_PARTICIPANT",
  CONTRACT_LOCK_FAILED: "CONTRACT_LOCK_FAILED",
  CONTRACT_RELEASE_FAILED: "CONTRACT_RELEASE_FAILED",
  CONTRACT_ALREADY_DISPUTED: "CONTRACT_ALREADY_DISPUTED",
  README_NOT_CONFIRMED: "README_NOT_CONFIRMED",
  DEMO_URL_REQUIRED: "DEMO_URL_REQUIRED",
  SOURCE_CODE_URL_REQUIRED: "SOURCE_CODE_URL_REQUIRED",

  // Extension
  EXTENSION_ALREADY_EXISTS: "EXTENSION_ALREADY_EXISTS",
  EXTENSION_NOT_FOUND: "EXTENSION_NOT_FOUND",
  EXTENSION_NOT_PENDING: "EXTENSION_NOT_PENDING",

  // Mutual cancel
  MUTUAL_CANCEL_ALREADY_EXISTS: "MUTUAL_CANCEL_ALREADY_EXISTS",
  MUTUAL_CANCEL_NOT_FOUND: "MUTUAL_CANCEL_NOT_FOUND",

  // MIA / Force cancel
  PING_NOT_ALLOWED: "PING_NOT_ALLOWED",
  FORCE_CANCEL_TOO_EARLY: "FORCE_CANCEL_TOO_EARLY",

  // Dispute
  DISPUTE_NOT_FOUND: "DISPUTE_NOT_FOUND",
  DISPUTE_ALREADY_OPEN: "DISPUTE_ALREADY_OPEN",
  DISPUTE_NOT_OPEN: "DISPUTE_NOT_OPEN",
  SETTLEMENT_AMOUNT_MISMATCH: "SETTLEMENT_AMOUNT_MISMATCH",

  // Milestone
  MILESTONE_NOT_FOUND: "MILESTONE_NOT_FOUND",
  MILESTONE_INVALID_STATUS: "MILESTONE_INVALID_STATUS",
  MILESTONE_AMOUNT_EXCEEDS_BUDGET: "MILESTONE_AMOUNT_EXCEEDS_BUDGET",

  // Review
  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",
  REVIEW_CONTRACT_NOT_DONE: "REVIEW_CONTRACT_NOT_DONE",
  REVIEW_NOT_PARTICIPANT: "REVIEW_NOT_PARTICIPANT",

  // Admin
  ADMIN_ONLY: "ADMIN_ONLY",

  // System
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND: "NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
